#############################################################################
# Makefile for building: GOP.app/Contents/MacOS/GOP
# Generated by qmake (3.1) (Qt 6.3.0)
# Project:  GOP.pro
# Template: app
# Command: /Users/yichen/Qt/6.3.0/macos/bin/qmake -o Makefile GOP.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -F/Users/yichen/Qt/6.3.0/macos/lib
QMAKE         = /Users/yichen/Qt/6.3.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/yichen/Qt/6.3.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/yichen/Qt/6.3.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GOP1.0.0
DISTDIR = /Users/yichen/Library/Mobile\ Documents/com~apple~CloudDocs/Macbook\ Pro\ M1/PKU/学习/程序设计实习/GOP/.tmp/GOP1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/yichen/Qt/6.3.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/yichen/Qt/6.3.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = attackwidget.cpp \
		big_class.cpp \
		endgamewidget.cpp \
		gamewindow.cpp \
		main.cpp \
		mainwidget.cpp \
		mousepos.cpp \
		movewidget.cpp \
		tpwidget.cpp qrc_res.cpp \
		moc_attackwidget.cpp \
		moc_endgamewidget.cpp \
		moc_gamewindow.cpp \
		moc_mainwidget.cpp \
		moc_mousepos.cpp \
		moc_movewidget.cpp \
		moc_tpwidget.cpp
OBJECTS       = attackwidget.o \
		big_class.o \
		endgamewidget.o \
		gamewindow.o \
		main.o \
		mainwidget.o \
		mousepos.o \
		movewidget.o \
		tpwidget.o \
		qrc_res.o \
		moc_attackwidget.o \
		moc_endgamewidget.o \
		moc_gamewindow.o \
		moc_mainwidget.o \
		moc_mousepos.o \
		moc_movewidget.o \
		moc_tpwidget.o
DIST          = /Users/yichen/Qt/6.3.0/macos/mkspecs/features/spec_pre.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/device_config.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/unix.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/mac.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/macx.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/sanitize.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/gcc-base.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/clang.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/clang-mac.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/qconfig.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3drender.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_nfc.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdf.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioning.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllint_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensors.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_websockets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webview.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt_functions.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt_config.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang/qmake.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/exclusive_builds.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/sdk.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/toolchain.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/toolchain.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/default_pre.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/default_pre.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resolve_config.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/default_post.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/default_post.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/objective_c.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qml_debug.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/mac.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/warn_on.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resources_functions.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resources.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/moc.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/unix/opengl.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/uic.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/unix/thread.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qmake_use.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/file_copies.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/rez.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/testcase_targets.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/exceptions.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/yacc.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/lex.prf \
		GOP.pro attackwidget.h \
		big_class.h \
		endgamewidget.h \
		gamewindow.h \
		mainwidget.h \
		mousepos.h \
		movewidget.h \
		tpwidget.h attackwidget.cpp \
		big_class.cpp \
		endgamewidget.cpp \
		gamewindow.cpp \
		main.cpp \
		mainwidget.cpp \
		mousepos.cpp \
		movewidget.cpp \
		tpwidget.cpp
QMAKE_TARGET  = GOP
DESTDIR       = 
TARGET        = GOP.app/Contents/MacOS/GOP

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP/GOP.pro


include /Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

GOP.app/Contents/MacOS/GOP: ui_attackwidget.h ui_endgamewidget.h ui_gamewindow.h ui_mainwidget.h ui_movewidget.h ui_tpwidget.h $(OBJECTS)  
	@test -d GOP.app/Contents/MacOS/ || mkdir -p GOP.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GOP.pro /Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang/qmake.conf /Users/yichen/Qt/6.3.0/macos/mkspecs/features/spec_pre.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/device_config.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/unix.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/mac.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/macx.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/sanitize.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/gcc-base.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/gcc-base-mac.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/clang.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/common/clang-mac.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/qconfig.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3drender.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_charts.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designer.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_gui.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_help.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_network.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_nfc.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdf.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioning.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllint_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensors.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sql.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svg.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_websockets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webview.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_xml.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt_functions.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt_config.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang/qmake.conf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/exclusive_builds.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/sdk.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/toolchain.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/toolchain.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/default_pre.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/default_pre.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resolve_config.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/default_post.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/default_post.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/objective_c.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qml_debug.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/mac.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/warn_on.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resources_functions.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resources.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/moc.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/unix/opengl.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/uic.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/unix/thread.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qmake_use.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/file_copies.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/rez.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/testcase_targets.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/exceptions.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/yacc.prf \
		/Users/yichen/Qt/6.3.0/macos/mkspecs/features/lex.prf \
		GOP.pro \
		res.qrc \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile GOP.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/spec_pre.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/device_config.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/unix.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/mac.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/macx.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/sanitize.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/gcc-base.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/gcc-base-mac.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/clang.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/common/clang-mac.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/qconfig.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_freetype.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_ext_libpng.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3danimation.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dcore.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dextras.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dinput.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3drender.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_charts.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_charts_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_chartsqml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core5compat.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_core_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_dbus.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designer.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_gui.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_help.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_help_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_linguist.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimedia.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_network.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_network_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_networkauth.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_nfc.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_opengl.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdf.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdf_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfquick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_png_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioning.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllint_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3d.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_repparser.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensors.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialbus.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialport.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_shadertools.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sql.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachine.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svg.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_testlib.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uitools.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webchannel.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_websockets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webview.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webview_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webviewquick.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_widgets.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_xml.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt_functions.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt_config.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang/qmake.conf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/exclusive_builds.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/sdk.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/toolchain.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/toolchain.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/default_pre.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/default_pre.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resolve_config.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/default_post.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/default_post.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/objective_c.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qml_debug.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/mac.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/warn_on.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qt.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resources_functions.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/resources.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/moc.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/unix/opengl.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/uic.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/unix/thread.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/qmake_use.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/file_copies.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/rez.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/mac/asset_catalogs.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/testcase_targets.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/exceptions.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/yacc.prf:
/Users/yichen/Qt/6.3.0/macos/mkspecs/features/lex.prf:
GOP.pro:
res.qrc:
/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile GOP.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

GOP.app/Contents/PkgInfo: 
	@test -d GOP.app/Contents || mkdir -p GOP.app/Contents
	@$(DEL_FILE) GOP.app/Contents/PkgInfo
	@echo "APPL????" > GOP.app/Contents/PkgInfo
GOP.app/Contents/Resources/empty.lproj: 
	@test -d GOP.app/Contents/Resources || mkdir -p GOP.app/Contents/Resources
	@touch GOP.app/Contents/Resources/empty.lproj
	
GOP.app/Contents/Info.plist: 
	@test -d GOP.app/Contents || mkdir -p GOP.app/Contents
	@$(DEL_FILE) GOP.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,XYC.GOP,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},XYC.GOP,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,GOP,g" -e "s,@LIBRARY@,GOP,g" -e "s,\$${EXECUTABLE_NAME},GOP,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang/Info.plist.app >GOP.app/Contents/Info.plist

all: Makefile \
		GOP.app/Contents/PkgInfo \
		GOP.app/Contents/Resources/empty.lproj \
		GOP.app/Contents/Info.plist GOP.app/Contents/MacOS/GOP

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents attackwidget.h big_class.h endgamewidget.h gamewindow.h mainwidget.h mousepos.h movewidget.h tpwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents attackwidget.cpp big_class.cpp endgamewidget.cpp gamewindow.cpp magic.cpp main.cpp mainwidget.cpp mousepos.cpp movewidget.cpp tpwidget.cpp weapon.cpp $(DISTDIR)/
	$(COPY_FILE) --parents attackwidget.ui endgamewidget.ui gamewindow.ui mainwidget.ui movewidget.ui tpwidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r GOP.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		/Users/yichen/Qt/6.3.0/macos/libexec/rcc
	/Users/yichen/Qt/6.3.0/macos/libexec/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_header_make_all: moc_attackwidget.cpp moc_endgamewidget.cpp moc_gamewindow.cpp moc_mainwidget.cpp moc_mousepos.cpp moc_movewidget.cpp moc_tpwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_attackwidget.cpp moc_endgamewidget.cpp moc_gamewindow.cpp moc_mainwidget.cpp moc_mousepos.cpp moc_movewidget.cpp moc_tpwidget.cpp
moc_attackwidget.cpp: attackwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib attackwidget.h -o moc_attackwidget.cpp

moc_endgamewidget.cpp: endgamewidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib endgamewidget.h -o moc_endgamewidget.cpp

moc_gamewindow.cpp: gamewindow.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		movewidget.h \
		tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		endgamewidget.h \
		attackwidget.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib gamewindow.h -o moc_gamewindow.cpp

moc_mainwidget.cpp: mainwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		gamewindow.h \
		movewidget.h \
		tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		endgamewidget.h \
		attackwidget.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib mainwidget.h -o moc_mainwidget.cpp

moc_mousepos.cpp: mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib mousepos.h -o moc_mousepos.cpp

moc_movewidget.cpp: movewidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib movewidget.h -o moc_movewidget.cpp

moc_tpwidget.cpp: tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/Users/yichen/Qt/6.3.0/macos/libexec/moc
	/Users/yichen/Qt/6.3.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=201703L -D__GNUC__=11 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=0 -I/Users/yichen/Qt/6.3.0/macos/mkspecs/macx-clang -I'/Users/yichen/Library/Mobile Documents/com~apple~CloudDocs/Macbook Pro M1/PKU/学习/程序设计实习/GOP' -I/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers -I/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++ -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/x86_64-w64-mingw32 -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include/c++/backward -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include -IC:/Qt/Tools/mingw1120_64/lib/gcc/x86_64-w64-mingw32/11.2.0/include-fixed -IC:/Qt/Tools/mingw1120_64/x86_64-w64-mingw32/include -F/Users/yichen/Qt/6.3.0/macos/lib tpwidget.h -o moc_tpwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_attackwidget.h ui_endgamewidget.h ui_gamewindow.h ui_mainwidget.h ui_movewidget.h ui_tpwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_attackwidget.h ui_endgamewidget.h ui_gamewindow.h ui_mainwidget.h ui_movewidget.h ui_tpwidget.h
ui_attackwidget.h: attackwidget.ui \
		/Users/yichen/Qt/6.3.0/macos/libexec/uic
	/Users/yichen/Qt/6.3.0/macos/libexec/uic attackwidget.ui -o ui_attackwidget.h

ui_endgamewidget.h: endgamewidget.ui \
		/Users/yichen/Qt/6.3.0/macos/libexec/uic
	/Users/yichen/Qt/6.3.0/macos/libexec/uic endgamewidget.ui -o ui_endgamewidget.h

ui_gamewindow.h: gamewindow.ui \
		/Users/yichen/Qt/6.3.0/macos/libexec/uic
	/Users/yichen/Qt/6.3.0/macos/libexec/uic gamewindow.ui -o ui_gamewindow.h

ui_mainwidget.h: mainwidget.ui \
		/Users/yichen/Qt/6.3.0/macos/libexec/uic
	/Users/yichen/Qt/6.3.0/macos/libexec/uic mainwidget.ui -o ui_mainwidget.h

ui_movewidget.h: movewidget.ui \
		/Users/yichen/Qt/6.3.0/macos/libexec/uic
	/Users/yichen/Qt/6.3.0/macos/libexec/uic movewidget.ui -o ui_movewidget.h

ui_tpwidget.h: tpwidget.ui \
		/Users/yichen/Qt/6.3.0/macos/libexec/uic
	/Users/yichen/Qt/6.3.0/macos/libexec/uic tpwidget.ui -o ui_tpwidget.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

attackwidget.o: attackwidget.cpp attackwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		ui_attackwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attackwidget.o attackwidget.cpp

big_class.o: big_class.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o big_class.o big_class.cpp

endgamewidget.o: endgamewidget.cpp endgamewidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_endgamewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o endgamewidget.o endgamewidget.cpp

gamewindow.o: gamewindow.cpp gamewindow.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		movewidget.h \
		tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		endgamewidget.h \
		attackwidget.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		ui_gamewindow.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QDebug \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QPainter \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qpainter.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QString \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qstring.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QStringList \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qstringlist.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QMessageBox \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QDateTime \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qdatetime.h \
		msghandlerwapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamewindow.o gamewindow.cpp

main.o: main.cpp mainwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		gamewindow.h \
		movewidget.h \
		tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		endgamewidget.h \
		attackwidget.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		gamewindow.h \
		movewidget.h \
		tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		endgamewidget.h \
		attackwidget.h \
		big_class.h \
		magic.cpp \
		weapon.cpp \
		mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QPaintEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QTextBrowser \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qtextbrowser.h \
		ui_mainwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QDebug \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

mousepos.o: mousepos.cpp mousepos.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QLabel \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qlabel.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/QMouseEvent \
		/Users/yichen/Qt/6.3.0/macos/lib/QtGui.framework/Headers/qevent.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QDebug \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qdebug.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/QString \
		/Users/yichen/Qt/6.3.0/macos/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mousepos.o mousepos.cpp

movewidget.o: movewidget.cpp movewidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		ui_movewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movewidget.o movewidget.cpp

tpwidget.o: tpwidget.cpp tpwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QWidget \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qwidget.h \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/QPushButton \
		/Users/yichen/Qt/6.3.0/macos/lib/QtWidgets.framework/Headers/qpushbutton.h \
		ui_tpwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tpwidget.o tpwidget.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_attackwidget.o: moc_attackwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attackwidget.o moc_attackwidget.cpp

moc_endgamewidget.o: moc_endgamewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_endgamewidget.o moc_endgamewidget.cpp

moc_gamewindow.o: moc_gamewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamewindow.o moc_gamewindow.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_mousepos.o: moc_mousepos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mousepos.o moc_mousepos.cpp

moc_movewidget.o: moc_movewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_movewidget.o moc_movewidget.cpp

moc_tpwidget.o: moc_tpwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tpwidget.o moc_tpwidget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GOP/bin || mkdir -p $(INSTALL_ROOT)/opt/GOP/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/GOP/bin/GOP.app
	
	$(QINSTALL) GOP.app $(INSTALL_ROOT)/opt/GOP/bin/GOP.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/GOP/bin/GOP.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GOP/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

